name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and upload
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          cache: true

      - name: Build
        run: go build -v ./cmd/usmparser

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: USMParser
          path: ./usmparser.exe
